# port for real-time output
output: 
    port: "tcp://192.168.137.1:6000"
    zmq_connection_type: 3

# sync node configuration
#sync:
#    euid: 0xdeca030000000001
#    interval: 0x17CDC00
#    position: [0.00, -1.00, 0.00]
#    port: "tcp://192.168.0.29:6000"
#    zmq_connection_type: 3

# calibration node configuration
#calibration:
#    euid: 0xdeca010000000007
#    position: [0.0, 0.0, 0.25]
#    window: 200

# anchor configuration
anchors:
    -   euid: 0xdeca020000000001
        port: "port unused in TWR"
        position: [-1.00, -1.00, 0.00]
    -   euid: 0xdeca020000000002
        port: "port unused in TWR"
        position: [1.00, -1.00, 0.00]
    -   euid: 0xdeca020000000003
        port: "port unused in TWR"
        position: [1.00, 1.00, 0.00]
    -   euid: 0xdeca020000000004
        port: "port unused in TWR"
        position: [-1.00, 1.00, 0.00]
#    -   euid: 0xdeca020000000005
#        port: /dev/ttyANCHOR5
#        position: [3.54, 0.02, 2.08]
#    -   euid: 0xdeca020000000006
#        port: /dev/ttyANCHOR6
#        position: [3.42, 3.52, 0.28]
#    -   euid: 0xdeca020000000007
#        port: /dev/ttyANCHOR7
#        position: [1.2, 3.49, 2.16]
#    -   euid: 0xdeca020000000008
#        port: /dev/ttyANCHOR8
#        position: [-1.17, 3.49, 2.17]

# tag configuration
#tags:
  #  -   euid: 0xdeca010000000001
  #	 port: "tcp://192.168.0.27:6050"

# whitelist for accepted tag euis
whitelist:
    -   0xdeca010000000001
    #-   0xdeca010000000002
    #-   0xdeca010000000003
    #-   0xdeca010000000004
    #-   0xdeca010000000005
    #-   0xdeca010000000006
    #-   0xdeca010000000007
    #-   0xdeca010000000008

# extended kalman filter configuration
#ekf:
#    processNoise: 0.05
#    measurementVariance: 0.1
#    initialInterval: 0.1
#    initialVariance: 100
#    initialVarianceDelta: 100
#    initialState: [0.5,0.5,0.5,0,0,0]

# local reference frame for coordinate conversion
# wgs84ref: point in the center of the local coordinate system
# wgs84axis: point along the x-axis of the local coordinate system
#lrf:
#    wgs84ref: [51.49146951, 7.4122313, 0]
#    wgs84axis: [51.49130178, 7.41264889, 0]